-- Run FIRST in phpMyAdmin on database mamsdb-35303030746b
-- Then import u454222977_mams_for_stackcp.sql
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `workshop_checklist_templates`;
DROP TABLE IF EXISTS `wialon_mother_accounts`;
DROP TABLE IF EXISTS `video_share_links`;
DROP TABLE IF EXISTS `vehicle_inspections`;
DROP TABLE IF EXISTS `user_preferences`;
DROP TABLE IF EXISTS `user_modules`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `trip_summaries`;
DROP TABLE IF EXISTS `tenant_modules`;
DROP TABLE IF EXISTS `tenant_fuel_module_configs`;
DROP TABLE IF EXISTS `tenant_files`;
DROP TABLE IF EXISTS `tenant_backup_settings`;
DROP TABLE IF EXISTS `tenant_backups`;
DROP TABLE IF EXISTS `tenant_api_keys`;
DROP TABLE IF EXISTS `tenants`;
DROP TABLE IF EXISTS `system_settings`;
DROP TABLE IF EXISTS `platform_integrations`;
DROP TABLE IF EXISTS `module_definitions`;
DROP TABLE IF EXISTS `mechanics`;
DROP TABLE IF EXISTS `marketplace_integrations`;
DROP TABLE IF EXISTS `maintenance_logs`;
DROP TABLE IF EXISTS `login_trust_logos`;
DROP TABLE IF EXISTS `login_slides`;
DROP TABLE IF EXISTS `integration_sync_logs`;
DROP TABLE IF EXISTS `geofences`;
DROP TABLE IF EXISTS `fuel_transactions`;
DROP TABLE IF EXISTS `fuel_sync_cursor`;
DROP TABLE IF EXISTS `fuel_station_uploads`;
DROP TABLE IF EXISTS `fuel_station_fills`;
DROP TABLE IF EXISTS `fuel_live_snapshots`;
DROP TABLE IF EXISTS `fleet_routes`;
DROP TABLE IF EXISTS `eco_driving_violations`;
DROP TABLE IF EXISTS `driver_performance_snapshots`;
DROP TABLE IF EXISTS `drivers`;
DROP TABLE IF EXISTS `data_sources`;
DROP TABLE IF EXISTS `command_logs`;
DROP TABLE IF EXISTS `breakdown_reports`;
DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `asset_status`;
DROP TABLE IF EXISTS `asset_mappings`;
DROP TABLE IF EXISTS `assets`;
DROP TABLE IF EXISTS `alerts`;
DROP TABLE IF EXISTS `activity_feed`;
SET FOREIGN_KEY_CHECKS=1;
